server.port=8080
spring.application.name=SUT_backend

# Configuración de Base de Datos (Tailscale)
# REEMPLAZA 100.X.Y.Z POR TU IP DE TRUE NAS
spring.datasource.url=jdbc:postgresql://100.67.45.103:5432/sut_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración futura de JWT
jwt.secret=secreto_super_seguro_para_firmar_tokens_cambiar_en_produccion_12345
jwt.expiration=86400000